notifications:
  email:
    - evantahler@gmail.com
language: node_js
node_js:
  - "0.10"
  - "0.11"
env:
  - "FAKEREDIS=true"
  - "FAKEREDIS=false"
branches:
  only:
    - master
    - develop
services:
  - redis-server
before_script:
  - npm install -g grunt-cli
notifications:
  webhooks:
    urls:
      - 'http://webhooks.nodejitsu.com/1/deploy'
      - 'https://webhooks.gitter.im/e/0b77e5af8eb07ea0ea0c'
    on_success: always
    on_failure: always
    on_start:   true
after_failure:
  - "cat /home/travis/builds/evantahler/actionhero/npm-debug.log"
