version: '2'
services:
  redis:
    image: redis
  actionhero:
    build: .
    ports:
     - "8080"
     - "5000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
