version: '2'
services:
  haproxy:
    image: dockercloud/haproxy
    links:
      - actionhero
    ports:
      - 80
      - 443
      - 5000
      - 1936
    environment:
      TCP_PORTS: 80,5000
      STATS_AUTH: actionhero:actionhero
      STATS_PORT: 1936
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
  actionhero:
    build: .
    ports:
     - 8080
     - 5000
    depends_on:
      - redis
    links:
      - redis
    environment:
      ENABLE_TCP_SERVER: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
